# Generated by Django 3.2.3 on 2023-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='name',
            field=models.CharField(default='Name', max_length=80),
        ),
    ]
