# Generated by Django 3.2.3 on 2023-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0002_auto_20230727_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
