# Generated by Django 4.2.7 on 2023-11-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptproject', '0008_auto_20230729_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=80)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('age', models.CharField(default='18', max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingSession',
        ),
    ]
